#! /bin/bash

repoName="$1"
serviceNickname="$2"
namespace="$3"

function echoUsage() {
  echo "USAGE: $(basename "$0") <service-name> <service-nickname> <github-namespace>"
}

if [ -z "$repoName" ]; then
  >&2 echoUsage
  exit 1
fi

if [ -z "$serviceNickname" ]; then
  >&2 echoUsage
  exit 2
fi

if [ -z "$namespace" ]; then
  >&2 echoUsage
  exit 3
fi

echo
echo "Setting up the @${namespace}/${repoName} service (${serviceNickname})"
echo "============================================================================="
echo

# Replace names in codebase

if command -v lsb_release &>/dev/null; then
  sedCommand="sed -i"
else
  sedCommand="sed -i '.bak'"
fi
$sedCommand "s/%{PROJECT""_NAME}/${repoName}/g" $(grep -rl PROJECT_NAME $PWD)
$sedCommand "s/%{PROJECT""_NICKNAME}/${serviceNickname}/g" $(grep -rl PROJECT_NICKNAME $PWD)
$sedCommand "s/%{NAME""SPACE}/${namespace}/g" $(grep -rl NAMESPACE $PWD)

find "$PWD" -name '*.bak' -delete || true

echo
echo "Done setting up. You should probably run \`git init\` and make an initial commit at this point."
echo

